### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by dalg24** [smartplus-team/smartplus#3]
this commit is responsible 9f043ec1b1c5cb23f06426f769fa9a2bbf177c6b
you deleted a bunch of header 
smartplus/Libraries/Continuum_Mechanics/constitutive.hpp
smartplus/Libraries/Homogenization/eshelby.hpp
smartplus/Libraries/Maths/rotation.hpp
etc.

**Comment by dalg24** [comment]
addressed by Dimitris
in commits
a326475fee052331a8d75be06f5b70503ee8236b
through
2b8bf670c2bca2997504e99e7f1fc497a775a674

**Comment by dimitris-chatz** [comment]
I don't know who you are mate, but you're doing God's work.

**Comment by dalg24** [comment]
Hi Dimitris. I am a good friend of Yves ;)
